### ISSUE TITLE
Compilation Warning for Lab 2

### ISSUE THREAD

**Issue by snatzehua** [nus-cs2030/2324-s2#77]
Hello, I submitted my code for Lab 2 to CodeCrunch and got the following compilation warning:

Exception in thread "main" com.sun.tools.classfile.Dependencies$ClassFileError
	at jdk.jdeps/com.sun.tools.jdeps.ClassFileReader.scan(ClassFileReader.java:165)
	at jdk.jdeps/com.sun.tools.jdeps.ClassFileReader.entries(ClassFileReader.java:114)
	at jdk.jdeps/com.sun.tools.jdeps.Archive.contains(Archive.java:95)
	at jdk.jdeps/com.sun.tools.jdeps.JdepsConfiguration$Builder.addRoot(JdepsConfiguration.java:495)
	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.buildConfig(JdepsTask.java:597)
	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:557)
	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:533)
	at jdk.jdeps/com.sun.tools.jdeps.Main.main(Main.java:49)
Caused by: com.sun.tools.classfile.ConstantPool$InvalidEntry: unexpected tag at #1: 118
	at jdk.jdeps/com.sun.tools.classfile.ConstantPool.<init>(ConstantPool.java:244)
	at jdk.jdeps/com.sun.tools.classfile.ClassFile.<init>(ClassFile.java:82)
	at jdk.jdeps/com.sun.tools.classfile.ClassFile.read(ClassFile.java:58)
	at jdk.jdeps/com.sun.tools.classfile.ClassFile.read(ClassFile.java:52)
	at jdk.jdeps/com.sun.tools.jdeps.ClassFileReader.scan(ClassFileReader.java:160)
	... 7 more
	
I am unsure of what is going on and have no idea how to address this warning. I would appreciate any help possible.

**Comment by BZAStudent** [comment]
Hi. There seem to be something blocking you from compiling.

**Comment by LimZiXiong** [comment]
I got the same warning as well but the autograder graded my submission without any problem despite the warning

**Comment by snatzehua** [comment]
> I got the same warning as well but the autograder graded my submission without any problem despite the warning

Same here

**Comment by BZAStudent** [comment]
Same here i got the warning too

**Comment by ZHD1987E** [comment]
Me three.

I can’t recreate the issue though…

**Comment by andrelau123** [comment]
Same I got the warning but the autograder graded my submission without any issues.

**Comment by EnzioKam** [comment]
There was some issue on codecrunch and we have regraded the existing submissions that are affected. It should be fixed now.
